### ISSUE TITLE
Undo action is allowed before swipe animation has completed on last card

### ISSUE THREAD

**Issue by mac-gallagher** [mac-gallagher/Shuffle#3]
#### Steps to reproduce:

- (Optional) Toggle slow animations on the simulator (⌘ + T)
- Programmatically swipe the last card on the card stack
- Quickly trigger an `undo` action

#### Expected behavior
It should not allow an `undo` action until the last card has finished its swipe animation

#### Actual behavior
It is possible to trigger an `undo` action while the last card is still animating. It is even possible to see two copies of the card at the same time

**Comment by appdude303** [comment]
I did some digging on this. I haven't decided upon a solution but I'll share what I think the problem is.

Where  the **SwipeCardDelegate** methods in**SwipeCardStack.swift** is implemented the function
`func card(didSwipe card: SwipeCard, with direction: SwipeDirection, forced: Bool)` calls `updateSwipeState(direction: direction)` which removes the card from `visibleCards` at index 0.

So when we try to undo a card the `topCard` is now the next card in the stack not the one we sent off the screen. This effects the `isEnabled` property. (defined below)

```
var isEnabled: Bool {
      return isUserInteractionEnabled && (topCard?.isUserInteractionEnabled ?? true)
}
```

The `undoLastSwipe` function in **SwipeCardStack.swift** checks for `isEnabled` and proceeds because the next card is ready according to this logic, even if the last card swiped is not.

### Why does this only happen on the last card?

This only happens on the last card because on all of the other card swipes the `isUserInteractionEnabled == false` in the `isEnabled` property. 

The `(topCard?.isUserInteractionEnabled ?? true) ` ends up always being true from what I can tell so far. 

On all of the other cards there is a card below that has an animation to complete, so it appears that the `isEnabled` property is working in this condition, however it just takes time for the animation to complete and set the `isUserInteractionEnable` property of the `SwipeCardStack` to true. 

You can **reproduce** the error on any card by removing the `isUserInteractionEnabled` part. like so:

```
var isEnabled: Bool {
      return (topCard?.isUserInteractionEnabled ?? true)
}
```
### Possible Quick Fix
I created a property called `lastCardSwiped` in **SwipeCardStack.swift**. 

In the delegate method implemented in **SwipeCardStack.swift**
`func card(didSwipe card: SwipeCard, with direction: SwipeDirection, forced: Bool)` 

I set a `lastCardSwiped = card`.

```
var isEnabled: Bool {
        return isUserInteractionEnabled && (topCard?.isUserInteractionEnabled ?? true) && (lastCardSwiped?.isUserInteractionEnabled ?? true)
    }
```

I don't think this is a permanent solution and I haven't really tested too much. I just wanted to document what I know here before I forget it!  :)


p.s. Thanks for sharing this library Mac! Much appreciated 🙏

**Comment by mac-gallagher** [comment]
Hey @appdude303, take a look at #27. You are correct that the `isEnabled ` property was not working properly. Thanks for looking into this and checking out the library! 🙏
