### ISSUE TITLE
Set Up Read The Docs with Sphinx 

### ISSUE THREAD

**Issue by mac-gallagher** [mac-gallagher/Shuffle#8]
First step is to just set up [Read The Docs](https://readthedocs.org) using whatever documentation already exists in the project. Adding more coverage will come later!

@purcellconsult is undertaking this project

**Comment by purcellconsult** [comment]
Here's what I came up with thus far: https://shuffle-docs.readthedocs.io/en/latest

**Comment by mac-gallagher** [comment]
Hey @purcellconsult,

Can you fork the repo and make a pull request with your changes? Let’s follow the same `docs` folder structure as in [this example](https://github.com/ericholscher/django-kong). I will follow up with some more comments there.

Also, can we rename the url host to “Shuffle” instead of “Shuffle-Docs?” If that is taken, let’s try “Shuffle-iOS”.

**Comment by mac-gallagher** [comment]
Hey @purcellconsult,

I have just checked and it looks like it is up to me to do most of the setup here (such as re-naming the url host). 

However, on second thought, I think we should hold off on setting up a Read The Docs for this repo. I'm not sure the project is complicated enough at the moment to warrant a new home for the documentation. If things change, I'll let you know and we can continue working on this. Sorry for not figuring this out earlier. Thanks for your time, and I hope you learned something new in the meantime!

**Comment by purcellconsult** [comment]
Hey Mac, hope you had a good Labor Day weekend. I just checked your email
and saw that you closed the issue before I could respond.


I wanted to help out on the project but I was also interested in getting
credit for the rst documentation.  Renaming the url host should not be a
big issue at this point, but if that's something you want to do then no
problem. I can send you the rst file so that you can have the read the
docs.


Thanks.


Doug

**Comment by mac-gallagher** [comment]
@purcellconsult as I mentioned you can still open a pull request which includes your rst file. We can leave it there for now and come back to it if/when the time is right.

**Comment by purcellconsult** [comment]
Sounds good, created pull request.
