### ISSUE TITLE
Animation completed callback or cardForItem(at: IndexPath) function?

### ISSUE THREAD

**Issue by wfgilman** [mac-gallagher/Shuffle#85]
I :heart: Shuffle! This issue is usage-related, not a bug or a feature. I want to trigger an event when the card is swiped right but I'm encountering two separate issues.

1. In `func cardStack(_ cardStack: SwipeCardStack, didSwipeCardAt index: Int, with direction: SwipeDirection)` there's no callback on when the animation is completed. I can't seem to trigger an undo _until_ the animation completes if I want to display the last card the user swiped.
2. I can't figure out how to get the card at the current index. I'm looking for something similar to the `UITableView` function `cellForRow(at: IndexPath)` so I can fetch the card being show to trigger a visual event on it, such as displaying an overlay.

I don't see any of these delegate methods exposed anywhere in the library. Are either of these things possible?

**Comment by mac-gallagher** [comment]
Hey @wfgilman! Glad you're enjoying the library!

1. This is intentional. Managing the displaying of cards and the internal state of the card stack is more complicated when allowing for swipe/undo actions _during_ while the card stack is already animating. I don't anticipate making any changes to this behavior
2. I'm glad you bring this up! I am actually working on adding support for this right now - stay tuned. Hope to have a PR up this week
